### ISSUE TITLE
Fix MD5 sum calculations of messages.

### ISSUE THREAD

**Issue by baalexander** [baalexander/rosnodejs#24]
The MD5 sum calculated in messages.js returns incorrect values. For example, std_msgs/String returns 5b89344b4d080ca499c0648063c40738 instead of 992ce8a1687cec8c8bd883ec73ca41d1.

md5 sum test cases should also be added to messages_test.js.

**Comment by maxired** [comment]
I will have a look about this

**Comment by baalexander** [comment]
Awesome! [ROS's genmsg implementation](https://github.com/ros/genmsg/blob/master/src/genmsg/gentools.py#L59,L109) or [roslua's implementation](https://github.com/timn/roslua/blob/master/src/roslua/msg_spec.lua#L276,L301) may be useful as a reference.

**Comment by maxired** [comment]
Does https://github.com/baalexander/rosnodejs/pull/26 fix this ?

**Comment by baalexander** [comment]
Yep, thanks again. I left a couple questions in the pull request.
